# docker-compose.infra.yml
version: '3.8'

services:
  redis:
    image: redis:7-alpine # Imagem consistente com outros compose files
    container_name: nistiprint-redis
    restart: always
    command: redis-server --appendonly yes # Ativa a persistência
    networks:
      - app-internal
    volumes:
      - redis_data:/data

  n8n:
    image: n8nio/n8n:latest
    container_name: nistiprint-n8n
    restart: always
    ports:
      - "5678:5678"
    networks:
      - gateway_net
      - app-internal
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_HOST=automacao.nistiprint.neolabs.com.br # Seu domínio do n8n
      - WEBHOOK_URL=https://automacao.nistiprint.neolabs.com.br/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_ENCRYPTION_KEY=Z3JlYXRwb25kc2hvdGJvZHlzaXRjaXRpemVubG9jYXRpb25hY3Rpb25zdGF0ZXNhd20=
      - BLING_WEBHOOK_SECRET=249c63780a28b044e5132a8318abb6b426d4285084e34c77333d262ec13d
    volumes:
      - n8n_data:/home/node/.n8n

networks:
  gateway_net:
    external: true
  app-internal:
    external: true

volumes:
  redis_data:
    name: nistiprint-redis-data # Nome explícito para o volume
  n8n_data: