# nistiprint-frontend/nginx.conf
server {
    listen 80;
    root   /usr/share/nginx/html;
    index  index.html;

    # Rota para qualquer requisição de página da SPA
    location / {
        try_files $uri $uri/ /index.html;
    }
}