# nistiprint-frontend/nginx.conf
server {
    listen 80;
    root   /usr/share/nginx/html; # Diretório onde o build do Vite estará
    index  index.html; # O arquivo principal do seu SPA

    # Configurações para servir o aplicativo SPA a partir do subcaminho /frontend/
    location /frontend/ {
        try_files $uri $uri/ /frontend/index.html;
        # A 'base' no Vite garante que os links internos no HTML/JS sejam /frontend/assets/...
    }

    # Redireciona acessos à raiz para o subcaminho do frontend.
    # Ex: acessar 'seu-dominio.com' irá para 'seu-dominio.com/frontend/'.
    location = / {
        return 301 /frontend/;
    }

    # Tratamento de erros para 404s que devem ser roteados pelo SPA
    error_page 404 /frontend/index.html;
    location = /frontend/index.html {
        internal;
    }
}
