from nistiprint_shared.models.ai_execution_log import *
from nistiprint_shared.models.bling_pedidos import *
from nistiprint_shared.models.bling_pedido_itens import *
from nistiprint_shared.models.bom import *
from nistiprint_shared.models.canal_venda import *
from nistiprint_shared.models.categoria import *
from nistiprint_shared.models.categoria_bom_regra import *
from nistiprint_shared.models.configuracao_aplicacao import *
from nistiprint_shared.models.contagem_auditoria import *
from nistiprint_shared.models.daily_production_log import *
from nistiprint_shared.models.demanda_item_origem import *
from nistiprint_shared.models.demanda_producao import *
from nistiprint_shared.models.deposito import *
from nistiprint_shared.models.entrega_producao import *
from nistiprint_shared.models.estoque_atual import *
from nistiprint_shared.models.fornecedor import *
from nistiprint_shared.models.fornecedor_insumo import *
from nistiprint_shared.models.installed_integration import *
from nistiprint_shared.models.integration_module import *
from nistiprint_shared.models.integration_refresh_log import *
from nistiprint_shared.models.notificacao import *
from nistiprint_shared.models.ordem_compra import *
from nistiprint_shared.models.ordem_producao import *
from nistiprint_shared.models.order_feedback import *
from nistiprint_shared.models.order_personalizations import *
from nistiprint_shared.models.pedido import *
from nistiprint_shared.models.permissao import *
from nistiprint_shared.models.plataforma import *
from nistiprint_shared.models.ponto_coleta import *
from nistiprint_shared.models.print_job import *
from nistiprint_shared.models.product import *
from nistiprint_shared.models.product_artwork import *
from nistiprint_shared.models.produto_externo import *
from nistiprint_shared.models.recurso_produtivo import *
from nistiprint_shared.models.regra_logistica import *
from nistiprint_shared.models.setor import *
from nistiprint_shared.models.shopee_orders import *
from nistiprint_shared.models.situacao_pedido import *
from nistiprint_shared.models.supabase_ai_log import *
from nistiprint_shared.models.supabase_chat import *
from nistiprint_shared.models.supabase_personalizacao import *
from nistiprint_shared.models.system_events_log import *
from nistiprint_shared.models.tag import *
from nistiprint_shared.models.transicao_situacao import *
from nistiprint_shared.models.unidade_medida import *
from nistiprint_shared.models.usuario import *
from nistiprint_shared.models.v2_chat_events import *
from nistiprint_shared.models.venda import *
from nistiprint_shared.models.webhook_log import *
