from .ai_execution_log import *
from .bling_pedidos import *
from .bling_pedido_itens import *
from .bom import *
from .canal_venda import *
from .categoria import *
from .categoria_bom_regra import *
from .configuracao_aplicacao import *
from .contagem_auditoria import *
from .daily_production_log import *
from .demanda_item_origem import *
from .demanda_producao import *
from .deposito import *
from .entrega_producao import *
from .estoque_atual import *
from .fornecedor import *
from .fornecedor_insumo import *
from .installed_integration import *
from .integration_module import *
from .integration_refresh_log import *
from .notificacao import *
from .ordem_compra import *
from .ordem_producao import *
from .order_feedback import *
from .order_personalizations import *
from .pedido import *
from .permissao import *
from .plataforma import *
from .ponto_coleta import *
from .print_job import *
from .product import *
from .product_artwork import *
from .produto_externo import *
from .recurso_produtivo import *
from .regra_logistica import *
from .setor import *
from .shopee_orders import *
from .situacao_pedido import *
from .supabase_ai_log import *
from .supabase_chat import *
from .supabase_personalizacao import *
from .system_events_log import *
from .tag import *
from .transicao_situacao import *
from .unidade_medida import *
from .usuario import *
from .v2_chat_events import *
from .venda import *
from .webhook_log import *
