-- Fundação do cadastro de produtos/variações.
-- Compatível com o legado: nenhuma coluna existente é removida nesta fase.

CREATE EXTENSION IF NOT EXISTS unaccent;

DO $$ BEGIN
  CREATE TYPE public.estagio_produto AS ENUM
    ('RASCUNHO', 'ARTE_PENDENTE', 'ARTE_OK', 'FICHA_OK', 'CANAL_OK', 'PUBLICADO', 'DESCONTINUADO');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE public.produtos
  ADD COLUMN IF NOT EXISTS estagio public.estagio_produto NOT NULL DEFAULT 'RASCUNHO',
  ADD COLUMN IF NOT EXISTS combinacao_chave text,
  ADD COLUMN IF NOT EXISTS arte_confirmada_em timestamptz,
  ADD COLUMN IF NOT EXISTS arte_confirmada_por uuid;

ALTER TABLE public.produtos
  ADD COLUMN IF NOT EXISTS ncm varchar(8),
  ADD COLUMN IF NOT EXISTS cest varchar(7),
  ADD COLUMN IF NOT EXISTS origem_mercadoria smallint,
  ADD COLUMN IF NOT EXISTS cfop_padrao_venda varchar(4),
  ADD COLUMN IF NOT EXISTS gtin varchar(14),
  ADD COLUMN IF NOT EXISTS gtin_embalagem varchar(14),
  ADD COLUMN IF NOT EXISTS marca text,
  ADD COLUMN IF NOT EXISTS fabricante text,
  ADD COLUMN IF NOT EXISTS mpn text,
  ADD COLUMN IF NOT EXISTS peso_liquido numeric(15,6),
  ADD COLUMN IF NOT EXISTS peso_bruto numeric(15,6),
  ADD COLUMN IF NOT EXISTS comprimento numeric(15,6),
  ADD COLUMN IF NOT EXISTS largura numeric(15,6),
  ADD COLUMN IF NOT EXISTS altura numeric(15,6),
  ADD COLUMN IF NOT EXISTS garantia_meses integer;

CREATE TABLE IF NOT EXISTS public.perfis_fiscais (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL UNIQUE,
  cst_icms varchar(3), cst_pis varchar(2), cst_cofins varchar(2),
  aliquota_icms numeric(8,4), aliquota_pis numeric(8,4), aliquota_cofins numeric(8,4),
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.produtos ADD COLUMN IF NOT EXISTS perfil_fiscal_id integer
  REFERENCES public.perfis_fiscais(id) ON DELETE SET NULL;

-- O estado comercial antigo é preservado, mas deixa de permitir que novos
-- produtos ativos sejam criados sem estágio publicado em uma fase posterior.
UPDATE public.produtos SET estagio = 'PUBLICADO'
 WHERE status = 'ativo' AND estagio = 'RASCUNHO';
UPDATE public.produtos SET estagio = 'RASCUNHO', status = 'inativo'
 WHERE status = 'rascunho';

CREATE UNIQUE INDEX IF NOT EXISTS ux_produtos_sku_normalizado
  ON public.produtos ((upper(regexp_replace(btrim(sku), '\\s+', ' ', 'g'))));

ALTER TABLE public.ficha_tecnica ADD COLUMN IF NOT EXISTS grupo text;

CREATE TABLE IF NOT EXISTS public.produto_eixos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo text NOT NULL UNIQUE,
  nome text NOT NULL,
  escopo text NOT NULL DEFAULT 'produto',
  ordem_sku integer,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.produto_eixo_opcoes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  eixo_id integer NOT NULL REFERENCES public.produto_eixos(id) ON DELETE CASCADE,
  codigo text NOT NULL,
  nome text NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (eixo_id, codigo)
);

CREATE TABLE IF NOT EXISTS public.produto_eixo_opcao_componentes (
  opcao_id integer NOT NULL REFERENCES public.produto_eixo_opcoes(id) ON DELETE CASCADE,
  componente_produto_id integer NOT NULL REFERENCES public.produtos(id) ON DELETE RESTRICT,
  quantidade numeric(15,6) NOT NULL DEFAULT 1 CHECK (quantidade > 0),
  PRIMARY KEY (opcao_id, componente_produto_id)
);

CREATE TABLE IF NOT EXISTS public.produto_pai_eixos (
  produto_pai_id integer NOT NULL REFERENCES public.produtos(id) ON DELETE CASCADE,
  eixo_id integer NOT NULL REFERENCES public.produto_eixos(id) ON DELETE RESTRICT,
  posicao integer NOT NULL DEFAULT 0,
  PRIMARY KEY (produto_pai_id, eixo_id)
);

CREATE TABLE IF NOT EXISTS public.produto_variacao_valores (
  produto_id integer NOT NULL REFERENCES public.produtos(id) ON DELETE CASCADE,
  eixo_id integer NOT NULL REFERENCES public.produto_eixos(id) ON DELETE RESTRICT,
  opcao_id integer NOT NULL REFERENCES public.produto_eixo_opcoes(id) ON DELETE RESTRICT,
  PRIMARY KEY (produto_id, eixo_id),
  UNIQUE (produto_id, opcao_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_produtos_parent_combinacao
  ON public.produtos (parent_id, combinacao_chave)
  WHERE parent_id IS NOT NULL AND combinacao_chave IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.produto_sku_historico (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto_id integer NOT NULL REFERENCES public.produtos(id) ON DELETE CASCADE,
  sku_anterior text NOT NULL,
  sku_novo text NOT NULL,
  alterado_por uuid,
  alterado_em timestamptz NOT NULL DEFAULT now(),
  virou_apelido boolean NOT NULL DEFAULT true
);

-- Permite o alias global descrito no modelo (plataforma NULL).
ALTER TABLE public.produtos_externos
  ADD COLUMN IF NOT EXISTS tipo varchar(20) NOT NULL DEFAULT 'SKU';
ALTER TABLE public.produtos_externos ALTER COLUMN plataforma DROP NOT NULL;

CREATE OR REPLACE FUNCTION public.registrar_alteracao_sku()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.sku IS DISTINCT FROM OLD.sku THEN
    INSERT INTO public.produto_sku_historico
      (produto_id, sku_anterior, sku_novo, alterado_por)
    VALUES (NEW.id, OLD.sku, NEW.sku, auth.uid());
    INSERT INTO public.produtos_externos (produto_id, codigo_externo, tipo, plataforma, metadados)
    SELECT OLD.id, OLD.sku, 'SKU', NULL, jsonb_build_object('origem', 'historico_sku')
    WHERE NOT EXISTS (
      SELECT 1 FROM public.produtos_externos
       WHERE produto_id = OLD.id AND codigo_externo = OLD.sku AND tipo = 'SKU'
    );
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_registrar_alteracao_sku ON public.produtos;
CREATE TRIGGER trg_registrar_alteracao_sku
  BEFORE UPDATE OF sku ON public.produtos
  FOR EACH ROW EXECUTE FUNCTION public.registrar_alteracao_sku();

CREATE TABLE IF NOT EXISTS public.tags (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(100) NOT NULL UNIQUE,
  descricao text,
  cor varchar(7),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.produto_tags (
  produto_id integer NOT NULL REFERENCES public.produtos(id) ON DELETE CASCADE,
  tag_id integer NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (produto_id, tag_id)
);

INSERT INTO public.tags (nome) VALUES
  ('Coleção 2026'), ('Coleção 2027'), ('Lançamento'), ('Descontinuar')
ON CONFLICT (nome) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.produto_anuncios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto_id integer REFERENCES public.produtos(id) ON DELETE SET NULL,
  integration_id integer REFERENCES public.installed_integrations(id) ON DELETE CASCADE,
  item_externo_id text NOT NULL,
  variacao_externa_id text,
  sku_anuncio text,
  titulo text,
  url text,
  status text NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo', 'pausado', 'encerrado')),
  preco_publicado numeric(15,4),
  estoque_publicado numeric(15,4),
  estoque_buffer numeric(15,4) NOT NULL DEFAULT 0,
  sincronizado_em timestamptz,
  ultimo_erro text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.produto_precos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto_id integer NOT NULL REFERENCES public.produtos(id) ON DELETE CASCADE,
  integration_id integer REFERENCES public.installed_integrations(id) ON DELETE CASCADE,
  tipo text NOT NULL CHECK (tipo IN ('padrao', 'promocional', 'minimo')),
  valor numeric(15,4) NOT NULL CHECK (valor >= 0),
  vigencia_inicio timestamptz NOT NULL DEFAULT now(),
  vigencia_fim timestamptz,
  UNIQUE (produto_id, integration_id, tipo, vigencia_inicio)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_produto_anuncios_chave_externa
  ON public.produto_anuncios (integration_id, item_externo_id, COALESCE(variacao_externa_id, ''));

CREATE INDEX IF NOT EXISTS ix_produto_variacao_eixo ON public.produto_variacao_valores (eixo_id, opcao_id);
CREATE INDEX IF NOT EXISTS ix_produto_anuncios_produto ON public.produto_anuncios (produto_id);
CREATE INDEX IF NOT EXISTS ix_produto_anuncios_externo ON public.produto_anuncios (item_externo_id, variacao_externa_id);

CREATE OR REPLACE VIEW public.v_produto_prontidao AS
SELECT p.id AS produto_id, p.estagio, p.sku, p.nome, p.categoria_id,
       EXISTS (SELECT 1 FROM public.ficha_tecnica f WHERE f.produto_pai_id = p.id) AS tem_ficha,
       EXISTS (
         SELECT 1 FROM public.ficha_tecnica f
          JOIN public.produtos c ON c.id = f.componente_id
          JOIN public.categorias cat ON cat.id = c.categoria_id
          WHERE f.produto_pai_id = p.id
            AND lower(cat.nome) LIKE '%miolo%'
       ) AS tem_miolo,
       EXISTS (
         SELECT 1 FROM public.ficha_tecnica f
          JOIN public.produtos c ON c.id = f.componente_id
          JOIN public.categorias cat ON cat.id = c.categoria_id
          WHERE f.produto_pai_id = p.id
            AND lower(cat.nome) LIKE '%capa%'
            AND lower(cat.nome) NOT LIKE '%contra%'
       ) AS tem_capa,
       EXISTS (
         SELECT 1 FROM public.ficha_tecnica f
          JOIN public.produtos c ON c.id = f.componente_id
          JOIN public.categorias cat ON cat.id = c.categoria_id
          WHERE f.produto_pai_id = p.id AND lower(cat.nome) LIKE '%contra%'
       ) AS tem_contra,
       EXISTS (
         SELECT 1 FROM public.ficha_tecnica f
          JOIN public.produtos c ON c.id = f.componente_id
          JOIN public.categorias cat ON cat.id = c.categoria_id
          WHERE f.produto_pai_id = p.id
            AND (lower(cat.nome) LIKE '%acabamento%' OR lower(cat.nome) LIKE '%encader%')
       ) AS tem_acabamento,
       EXISTS (
         SELECT 1 FROM public.categorias cat
          WHERE cat.id = p.categoria_id AND cat.permite_arte
       ) OR EXISTS (
         SELECT 1 FROM public.ficha_tecnica f
          JOIN public.produtos c ON c.id = f.componente_id
          JOIN public.categorias cat ON cat.id = c.categoria_id
          WHERE f.produto_pai_id = p.id AND cat.permite_arte
       ) AS exige_arte,
       p.arte_confirmada_em IS NOT NULL AS arte_confirmada,
       EXISTS (SELECT 1 FROM public.produtos_externos e WHERE e.produto_id = p.id) AS tem_apelido_externo,
       p.preco_custo IS NOT NULL AND p.preco_custo > 0 AS tem_custo,
       EXISTS (SELECT 1 FROM public.produto_variacao_valores v WHERE v.produto_id = p.id) AS eixos_completos,
       CASE WHEN p.estagio = 'RASCUNHO' THEN 'ARTE_PENDENTE'::public.estagio_produto
            WHEN p.estagio = 'ARTE_PENDENTE' THEN 'ARTE_OK'::public.estagio_produto
            WHEN p.estagio = 'ARTE_OK' THEN 'FICHA_OK'::public.estagio_produto
            WHEN p.estagio = 'FICHA_OK' THEN 'CANAL_OK'::public.estagio_produto
            WHEN p.estagio = 'CANAL_OK' THEN 'PUBLICADO'::public.estagio_produto
            ELSE p.estagio END AS proximo_estagio,
       ARRAY_REMOVE(ARRAY[
         CASE WHEN NOT EXISTS (SELECT 1 FROM public.ficha_tecnica f WHERE f.produto_pai_id = p.id) THEN 'sem ficha' END,
         CASE WHEN NOT EXISTS (SELECT 1 FROM public.produtos_externos e WHERE e.produto_id = p.id) THEN 'sem apelido externo' END,
         CASE WHEN p.preco_custo IS NULL OR p.preco_custo <= 0 THEN 'sem custo' END
       ], NULL) AS pendencias
FROM public.produtos p;