-- Backfill seguro dos SKUs atuais como aliases globais.
-- Não altera produtos, pedidos ou aliases existentes.

CREATE TABLE IF NOT EXISTS public.produto_alias_conflitos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  produto_id integer NOT NULL REFERENCES public.produtos(id) ON DELETE CASCADE,
  codigo_externo text NOT NULL,
  produto_alias_id integer REFERENCES public.produtos(id) ON DELETE SET NULL,
  observado_em timestamptz NOT NULL DEFAULT now(),
  resolvido_em timestamptz,
  UNIQUE (produto_id, codigo_externo, produto_alias_id)
);

-- Registra colisões normalizadas sem escolher silenciosamente um produto.
INSERT INTO public.produto_alias_conflitos (produto_id, codigo_externo, produto_alias_id)
SELECT p.id, p.sku, e.produto_id
  FROM public.produtos p
  JOIN public.produtos_externos e
    ON upper(regexp_replace(btrim(e.codigo_externo), '\s+', ' ', 'g')) =
       upper(regexp_replace(btrim(p.sku), '\s+', ' ', 'g'))
   AND e.plataforma IS NULL
   AND e.produto_id <> p.id
ON CONFLICT DO NOTHING;

-- O alias é criado somente quando o código ainda não aponta para outro
-- produto no espaço normalizado. O SKU interno continua sendo a precedência 0.
INSERT INTO public.produtos_externos
  (produto_id, codigo_externo, tipo, plataforma, metadados)
SELECT p.id, p.sku, 'SKU', NULL,
       jsonb_build_object('origem', 'backfill_sku_interno', 'produto_id_origem', p.id)
  FROM public.produtos p
 WHERE NOT EXISTS (
   SELECT 1
     FROM public.produtos_externos e
    WHERE e.plataforma IS NULL
      AND upper(regexp_replace(btrim(e.codigo_externo), '\s+', ' ', 'g')) =
          upper(regexp_replace(btrim(p.sku), '\s+', ' ', 'g'))
      AND e.produto_id <> p.id
 )
 AND NOT EXISTS (
   SELECT 1
     FROM public.produtos_externos e
    WHERE e.produto_id = p.id
      AND e.tipo = 'SKU'
      AND e.plataforma IS NULL
      AND upper(regexp_replace(btrim(e.codigo_externo), '\s+', ' ', 'g')) =
          upper(regexp_replace(btrim(p.sku), '\s+', ' ', 'g'))
 );

CREATE INDEX IF NOT EXISTS ix_produto_alias_conflitos_pendente
  ON public.produto_alias_conflitos (resolvido_em)
  WHERE resolvido_em IS NULL;