-- Conferencia de arquivo como uma terceira origem do escopo de despacho.
-- O arquivo e descartavel; as linhas normalizadas, o filtro e o recorte ficam
-- aqui para permitir ingest e retry de ERP sem novo upload.

CREATE TABLE IF NOT EXISTS public.conferencias_arquivo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arquivo_nome text NOT NULL,
    module_id text NOT NULL,
    marketplace_integration_id integer REFERENCES public.installed_integrations(id),
    filtro jsonb NOT NULL DEFAULT '{}'::jsonb,
    total_linhas integer NOT NULL DEFAULT 0,
    total_refs integer NOT NULL DEFAULT 0,
    descartes jsonb NOT NULL DEFAULT '[]'::jsonb,
    linhas jsonb NOT NULL DEFAULT '[]'::jsonb,
    pedido_ids integer[] NOT NULL DEFAULT '{}'::integer[],
    nao_encontrados text[] NOT NULL DEFAULT '{}'::text[],
    fora_da_torre jsonb NOT NULL DEFAULT '[]'::jsonb,
    ingest_resultado jsonb,
    erp_resultado jsonb,
    demanda_id integer REFERENCES public.demandas_producao(id),
    criado_por text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_conferencias_arquivo_created_at
    ON public.conferencias_arquivo (created_at DESC);

ALTER TABLE public.conferencias_arquivo ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE ON public.conferencias_arquivo TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.conferencias_arquivo_id_seq TO service_role;

COMMENT ON TABLE public.conferencias_arquivo IS
    'Recorte auditavel de uma planilha: linhas normalizadas, filtro aplicado e pedidos resolvidos.';

DO $migration_view$
BEGIN
  -- A view equivalente ja existe em producao e possui regras/opcoes adicionais
  -- de seguranca. Preserve-a; a definicao abaixo e apenas o fallback para um
  -- banco novo que ainda nao recebeu a familia de migrations do despacho.
  IF NOT EXISTS (
      SELECT 1
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
       WHERE n.nspname = 'public'
         AND c.relname = 'vw_pedidos_pendentes_despacho'
         AND c.relkind = 'v'
  ) THEN
    EXECUTE $fn$
CREATE VIEW public.vw_pedidos_pendentes_despacho AS
SELECT p.*
  FROM public.pedidos p
  LEFT JOIN public.modalidades_logisticas m ON m.id = p.modalidade_logistica_id
 WHERE p.despachado_em IS NULL
   AND p.situacao_pedido_id IN (2, 3, 4)
   AND COALESCE(m.entra_na_torre, NOT COALESCE(p.is_fulfillment, false));
$fn$;
  END IF;
END;
$migration_view$;

-- Mesmo predicado da arvore. A lista do arquivo e sempre a autoridade; a
-- torre nao acrescenta pedidos que nao estavam no filtro.
DO $migration_escopo$
BEGIN
  IF NOT EXISTS (
      SELECT 1 FROM pg_proc p
      JOIN pg_namespace n ON n.oid = p.pronamespace
       WHERE n.nspname = 'public'
         AND p.proname = 'despacho_escopo_lote'
         AND p.pronargs = 4
         AND p.proargtypes[0] = 'integer'::regtype::oid
         AND p.proargtypes[1] = 'integer[]'::regtype::oid
         AND p.proargtypes[2] = 'text[]'::regtype::oid
         AND p.proargtypes[3] = 'date'::regtype::oid
  ) THEN
    EXECUTE $fn$
CREATE OR REPLACE FUNCTION public.despacho_escopo_lote(
    p_integration_id integer,
    p_modalidade_ids integer[] DEFAULT NULL,
    p_horizonte text[] DEFAULT ARRAY['atrasado', 'hoje'],
    p_data date DEFAULT CURRENT_DATE
)
RETURNS SETOF integer
LANGUAGE sql STABLE
AS $body$
    SELECT p.id
      FROM public.pedidos p
      LEFT JOIN public.modalidades_logisticas m ON m.id = p.modalidade_logistica_id
     WHERE p.despachado_em IS NULL
       AND p.situacao_pedido_id IN (2, 3, 4)
       AND COALESCE(m.entra_na_torre, NOT COALESCE(p.is_fulfillment, false))
       AND p.marketplace_integration_id IS NOT DISTINCT FROM p_integration_id
       AND (p_modalidade_ids IS NULL OR cardinality(p_modalidade_ids) = 0
            OR p.modalidade_logistica_id = ANY (p_modalidade_ids)
            OR (p.modalidade_logistica_id IS NULL AND NULL = ANY(p_modalidade_ids)))
       AND CASE
             WHEN p.data_limite_envio IS NULL THEN 'sem_prazo'
             WHEN p.data_limite_envio::date < p_data THEN 'atrasado'
             WHEN p.data_limite_envio::date = p_data THEN 'hoje'
             WHEN p.data_limite_envio::date = p_data + 1 THEN 'amanha'
             ELSE 'depois'
           END = ANY (COALESCE(p_horizonte, ARRAY['atrasado', 'hoje']))
     ORDER BY p.compromisso_logistico_em NULLS FIRST, p.id;
$body$;
$fn$;
  END IF;
END;
$migration_escopo$;

-- A mesma leitura usada no lancamento, sem criar demanda. O miolo e resolvido
-- pela ficha tecnica quando o componente esta identificado como miolo; linhas
-- sem produto ou sem BOM continuam validas e ficam marcadas para conferencia.
DO $migration$
BEGIN
  -- A producao ja possui uma versao mais completa desta RPC. Nao a substitua
  -- durante o rollout: alem de perder a resolucao por SKU/ficha, o PostgreSQL
  -- nao permite trocar o formato de retorno de uma funcao com OR REPLACE.
  IF NOT EXISTS (
      SELECT 1
        FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
       WHERE n.nspname = 'public'
         AND p.proname = 'despacho_consolidar_pedidos'
         AND p.pronargs = 1
         AND p.proargtypes[0] = 'integer[]'::regtype::oid
  ) THEN
    EXECUTE $fn$
CREATE OR REPLACE FUNCTION public.despacho_consolidar_pedidos(
    p_pedido_ids integer[]
)
RETURNS TABLE (
    produto_id integer,
    sku_externo text,
    descricao text,
    quantidade numeric,
    pedido_ids integer[],
    id_produto_miolo integer,
    miolo_nome text,
    miolo_rank integer,
    contabiliza_estoque boolean
)
LANGUAGE sql STABLE
AS $body$
WITH linhas AS (
    SELECT
        COALESCE(ip.produto_id, p.id) AS produto_id,
        ip.sku_externo::text AS sku_externo,
        ip.descricao::text AS descricao,
        ip.quantidade,
        ip.pedido_id
      FROM public.itens_pedido ip
      LEFT JOIN public.produtos p
        ON p.id = ip.produto_id
     WHERE ip.pedido_id = ANY(COALESCE(p_pedido_ids, '{}'::integer[]))
), agrupadas AS (
    SELECT
        produto_id,
        sku_externo,
        descricao,
        sum(quantidade)::numeric AS quantidade,
        array_agg(DISTINCT pedido_id ORDER BY pedido_id)::integer[] AS pedido_ids
      FROM linhas
     GROUP BY produto_id, sku_externo, descricao
), com_miolo AS (
    SELECT a.*,
           miolo.id_produto_miolo,
           miolo.miolo_nome
      FROM agrupadas a
      LEFT JOIN LATERAL (
        SELECT comp.id AS id_produto_miolo, comp.nome::text AS miolo_nome
          FROM public.ficha_tecnica ft
          JOIN public.produtos comp ON comp.id = ft.componente_id
         WHERE ft.produto_pai_id = a.produto_id
           AND (
               upper(COALESCE(comp.tipo_material, '')) LIKE '%MIOLO%'
               OR upper(COALESCE(comp.nome, '')) LIKE '%MIOLO%'
               OR upper(COALESCE(comp.sku, '')) LIKE '%MIOLO%'
           )
         ORDER BY ft.id
         LIMIT 1
      ) miolo ON true
)
SELECT produto_id,
       sku_externo,
       descricao,
       quantidade,
       pedido_ids,
       id_produto_miolo,
       miolo_nome,
       dense_rank() OVER (ORDER BY COALESCE(miolo_nome, descricao, sku_externo, produto_id::text))::integer AS miolo_rank,
       (produto_id IS NOT NULL) AS contabiliza_estoque
  FROM com_miolo
 ORDER BY miolo_rank, COALESCE(descricao, sku_externo, produto_id::text);
$body$;
$fn$;
  END IF;
END;
$migration$;

-- Seleciona pedidos arbitrarios, com guarda contra dois rascunhos para o mesmo
-- pedido. A materializacao usa a mesma tabela de itens do fluxo da torre.
CREATE OR REPLACE FUNCTION public.despacho_lancar_pedidos(
    p_pedido_ids integer[],
    p_nome text DEFAULT NULL,
    p_user_id text DEFAULT 'System',
    p_observacoes text DEFAULT NULL,
    p_escopo jsonb DEFAULT '{}'::jsonb
)
RETURNS TABLE (
    out_demanda_id integer,
    out_demanda_codigo text,
    out_total_pedidos integer,
    out_total_itens numeric,
    out_complementar boolean,
    out_ja_em_rascunho jsonb
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_ids integer[];
    v_demanda integer;
    v_codigo text;
    v_nome text;
    v_total numeric;
    v_conflicts jsonb;
    v_conferencia text := p_escopo ->> 'conferencia_id';
BEGIN
    IF v_conferencia IS NOT NULL THEN
        SELECT d.id, d.demanda_id INTO v_demanda, v_codigo
          FROM public.demandas_producao d
         WHERE d.escopo_despacho ->> 'conferencia_id' = v_conferencia
           AND d.status <> 'CANCELADO'
         ORDER BY d.id DESC LIMIT 1;
        IF v_demanda IS NOT NULL THEN
            SELECT COALESCE(sum(i.quantidade), 0) INTO v_total
              FROM public.itens_demanda i WHERE i.demanda_id = v_demanda;
            RETURN QUERY SELECT v_demanda, v_codigo, (SELECT count(*)::integer FROM public.demandas_pedidos dp WHERE dp.demanda_id = v_demanda), COALESCE(v_total, 0), false, '[]'::jsonb;
            RETURN;
        END IF;
    END IF;

    SELECT array_agg(DISTINCT p.id ORDER BY p.id)
      INTO v_ids
      FROM public.pedidos p
     WHERE p.id = ANY(COALESCE(p_pedido_ids, '{}'::integer[]))
       AND p.despachado_em IS NULL
       AND p.situacao_pedido_id IN (2, 3, 4);

    SELECT COALESCE(jsonb_agg(jsonb_build_object(
                'pedido_id', dp.pedido_id,
                'demanda_id', dp.demanda_id,
                'demanda_codigo', d.demanda_id,
                'descricao', d.descricao
           ) ORDER BY dp.pedido_id), '[]'::jsonb)
      INTO v_conflicts
      FROM public.demandas_pedidos dp
      JOIN public.demandas_producao d ON d.id = dp.demanda_id
     WHERE dp.pedido_id = ANY(COALESCE(v_ids, '{}'::integer[]))
       AND d.status = 'RASCUNHO';

    SELECT array_agg(x.pedido_id ORDER BY x.pedido_id) INTO v_ids
      FROM (
        SELECT unnest(COALESCE(v_ids, '{}'::integer[])) AS pedido_id
        EXCEPT
        SELECT (item->>'pedido_id')::integer FROM jsonb_array_elements(v_conflicts) item
      ) x;

    IF COALESCE(array_length(v_ids, 1), 0) = 0 THEN
        RAISE EXCEPTION 'Todos os pedidos ja estao em outro rascunho' USING ERRCODE = 'unique_violation', DETAIL = v_conflicts::text;
    END IF;

    v_codigo := COALESCE(NULLIF(p_escopo ->> 'nome', ''), 'DESPACHO-ARQUIVO-' || to_char(now(), 'YYYYMMDDHH24MISS'));
    v_nome := COALESCE(p_nome, v_codigo);
    INSERT INTO public.demandas_producao (
        demanda_id, descricao, status, tipo_demanda, data_entrega,
        observacoes, escopo_despacho, pedido_numero
    ) VALUES (
        v_codigo, v_nome, 'RASCUNHO', 'PLATAFORMA', CURRENT_DATE,
        p_observacoes, COALESCE(p_escopo, '{}'::jsonb) || jsonb_build_object('lancado_por', p_user_id, 'lancado_em', now()),
        array_length(v_ids, 1)::text || ' pedidos'
    ) RETURNING id INTO v_demanda;

    INSERT INTO public.itens_demanda (
        demanda_id, produto_id, sku, descricao, quantidade, dados_adicionais,
        miolo_nome, id_produto_miolo
    )
    SELECT v_demanda,
           COALESCE(ip.produto_id, produto.id),
           max(ip.sku_externo),
           max(ip.descricao),
           sum(ip.quantidade),
           '{}'::jsonb,
           max(miolo.miolo_nome),
           max(miolo.id_produto_miolo)
      FROM public.itens_pedido ip
      LEFT JOIN public.produtos produto
        ON produto.id = ip.produto_id
      LEFT JOIN LATERAL (
        SELECT comp.id AS id_produto_miolo, comp.nome::text AS miolo_nome
          FROM public.ficha_tecnica ft
          JOIN public.produtos comp ON comp.id = ft.componente_id
         WHERE ft.produto_pai_id = COALESCE(ip.produto_id, produto.id)
           AND (
               upper(COALESCE(comp.tipo_material, '')) LIKE '%MIOLO%'
               OR upper(COALESCE(comp.nome, '')) LIKE '%MIOLO%'
               OR upper(COALESCE(comp.sku, '')) LIKE '%MIOLO%'
           )
         ORDER BY ft.id
         LIMIT 1
      ) miolo ON true
     WHERE ip.pedido_id = ANY(v_ids)
     GROUP BY COALESCE(ip.produto_id, produto.id),
              COALESCE(ip.sku_externo, ip.descricao, ip.produto_id::text);

    INSERT INTO public.demandas_pedidos (demanda_id, pedido_id)
    SELECT v_demanda, unnest(v_ids) ON CONFLICT DO NOTHING;

    SELECT COALESCE(sum(i.quantidade), 0) INTO v_total
      FROM public.itens_demanda i WHERE i.demanda_id = v_demanda;
    RETURN QUERY SELECT v_demanda, v_codigo, array_length(v_ids, 1), COALESCE(v_total, 0), false, v_conflicts;
END;
$$;

-- Compatibilidade para o fluxo da torre enquanto ele migra para a selecao
-- explicita. A origem continua sendo resolvida pelo mesmo conjunto e a nova
-- guarda de rascunho fica centralizada em despacho_lancar_pedidos.
DO $migration_lote$
BEGIN
  IF NOT EXISTS (
      SELECT 1 FROM pg_proc p
      JOIN pg_namespace n ON n.oid = p.pronamespace
       WHERE n.nspname = 'public'
         AND p.proname = 'despacho_lancar_lote'
         AND p.pronargs = 7
         AND p.proargtypes[0] = 'integer'::regtype::oid
         AND p.proargtypes[1] = 'integer[]'::regtype::oid
         AND p.proargtypes[2] = 'text[]'::regtype::oid
         AND p.proargtypes[3] = 'date'::regtype::oid
         AND p.proargtypes[4] = 'text'::regtype::oid
         AND p.proargtypes[5] = 'text'::regtype::oid
         AND p.proargtypes[6] = 'text'::regtype::oid
  ) THEN
    EXECUTE $fn$
CREATE OR REPLACE FUNCTION public.despacho_lancar_lote(
    p_integration_id integer,
    p_modalidade_ids integer[] DEFAULT NULL,
    p_horizonte text[] DEFAULT ARRAY['atrasado', 'hoje'],
    p_data date DEFAULT CURRENT_DATE,
    p_nome text DEFAULT NULL,
    p_user_id text DEFAULT 'System',
    p_observacoes text DEFAULT NULL
)
RETURNS TABLE (
    out_demanda_id integer,
    out_demanda_codigo text,
    out_total_pedidos integer,
    out_total_itens numeric,
    out_complementar boolean
)
LANGUAGE plpgsql
AS $body$
DECLARE
    v_ids integer[];
    v_result record;
BEGIN
    SELECT array_agg(id ORDER BY id) INTO v_ids
      FROM public.despacho_escopo_lote(p_integration_id, p_modalidade_ids, p_horizonte, p_data) AS id;
    IF COALESCE(array_length(v_ids, 1), 0) = 0 THEN
        RAISE EXCEPTION 'Escopo vazio' USING ERRCODE = 'no_data_found';
    END IF;
    SELECT * INTO v_result FROM public.despacho_lancar_pedidos(
        v_ids, p_nome, p_user_id, p_observacoes,
        jsonb_build_object('integration_id', p_integration_id, 'modalidade_ids', p_modalidade_ids, 'horizonte', p_horizonte, 'data_operacional', p_data)
    );
    RETURN QUERY SELECT v_result.out_demanda_id, v_result.out_demanda_codigo,
        v_result.out_total_pedidos, v_result.out_total_itens, v_result.out_complementar;
END;
$body$;
$fn$;
  END IF;
END;
$migration_lote$;

-- Publicacao e o unico ponto que tira pedidos da torre.
DO $migration_publicar$
BEGIN
  IF NOT EXISTS (
      SELECT 1 FROM pg_proc p
      JOIN pg_namespace n ON n.oid = p.pronamespace
       WHERE n.nspname = 'public'
         AND p.proname = 'despacho_publicar_demanda'
         AND p.pronargs = 2
         AND p.proargtypes[0] = 'integer'::regtype::oid
         AND p.proargtypes[1] = 'text'::regtype::oid
  ) THEN
    EXECUTE $fn$
CREATE OR REPLACE FUNCTION public.despacho_publicar_demanda(
    p_demanda_id integer,
    p_user_id text DEFAULT 'System'
)
RETURNS TABLE (out_demanda_codigo text, out_total_pedidos integer, out_total_itens numeric)
LANGUAGE plpgsql
AS $body$
DECLARE
    v_status text;
BEGIN
    SELECT d.status INTO v_status FROM public.demandas_producao d WHERE d.id = p_demanda_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Demanda nao encontrada'; END IF;
    IF v_status <> 'RASCUNHO' THEN RAISE EXCEPTION 'so rascunho pode ser publicado'; END IF;
    UPDATE public.demandas_producao SET status = 'AGUARDANDO', publicado_em = now(), updated_at = now() WHERE id = p_demanda_id;
    UPDATE public.pedidos p SET despachado_em = now()
      WHERE p.id IN (SELECT pedido_id FROM public.demandas_pedidos WHERE demanda_id = p_demanda_id);
    RETURN QUERY
      SELECT d.demanda_id, (SELECT count(*)::integer FROM public.demandas_pedidos WHERE demanda_id = d.id),
             (SELECT COALESCE(sum(quantidade), 0) FROM public.itens_demanda WHERE demanda_id = d.id)
        FROM public.demandas_producao d WHERE d.id = p_demanda_id;
END;
$body$;
$fn$;
  END IF;
END;
$migration_publicar$;

GRANT EXECUTE ON FUNCTION public.despacho_escopo_lote(integer, integer[], text[], date)
    TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.despacho_consolidar_pedidos(integer[])
    TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.despacho_lancar_pedidos(integer[], text, text, text, jsonb)
    TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.despacho_lancar_lote(integer, integer[], text[], date, text, text, text)
    TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.despacho_publicar_demanda(integer, text)
    TO authenticated, service_role;
