-- Post-sale chat intake and personalization, isolated from the Shopee AI tables.
CREATE TABLE IF NOT EXISTS public.mercadolivre_chat_inbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marketplace_integration_id integer REFERENCES public.installed_integrations(id) ON DELETE SET NULL,
    account_user_id text,
    application_id text,
    provider_message_id text NOT NULL,
    dedupe_key text NOT NULL UNIQUE,
    webhook_event_id bigint REFERENCES public.webhook_events(id) ON DELETE SET NULL,
    actions jsonb NOT NULL DEFAULT '[]'::jsonb,
    raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'pending'
      CHECK (status IN ('pending','processing','retry','unmatched','done','failed')),
    attempts integer NOT NULL DEFAULT 0,
    available_at timestamptz NOT NULL DEFAULT now(),
    lease_until timestamptz,
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_ml_chat_inbox_account_status
  ON public.mercadolivre_chat_inbox(marketplace_integration_id, status, available_at, created_at);
CREATE INDEX IF NOT EXISTS ix_ml_chat_inbox_unmatched
  ON public.mercadolivre_chat_inbox(application_id, account_user_id, status) WHERE status='unmatched';

CREATE TABLE IF NOT EXISTS public.mercadolivre_chat_conversations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marketplace_integration_id integer NOT NULL REFERENCES public.installed_integrations(id) ON DELETE CASCADE,
    pack_id text NOT NULL,
    seller_id text NOT NULL,
    site_id text,
    order_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
    last_message_at timestamptz,
    last_synced_at timestamptz,
    context_hash text,
    ai_status text,
    last_ai_executed_at timestamptz,
    needs_review boolean NOT NULL DEFAULT false,
    last_error text,
    raw_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (marketplace_integration_id, pack_id, seller_id)
);
CREATE INDEX IF NOT EXISTS ix_ml_chat_conversations_recent
  ON public.mercadolivre_chat_conversations(marketplace_integration_id, last_message_at DESC);

CREATE TABLE IF NOT EXISTS public.mercadolivre_chat_messages (
    marketplace_integration_id integer NOT NULL REFERENCES public.installed_integrations(id) ON DELETE CASCADE,
    provider_message_id text NOT NULL,
    pack_id text NOT NULL,
    seller_id text NOT NULL,
    from_user_id text,
    to_user_id text,
    sender_role text NOT NULL DEFAULT 'unknown'
      CHECK (sender_role IN ('buyer','seller','agent','unknown')),
    message_type text,
    text_content text,
    created_at timestamptz,
    moderation_status text,
    attachments jsonb NOT NULL DEFAULT '[]'::jsonb,
    raw_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    webhook_event_id bigint REFERENCES public.webhook_events(id) ON DELETE SET NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (marketplace_integration_id, provider_message_id)
);
CREATE INDEX IF NOT EXISTS ix_ml_chat_messages_pack_time
  ON public.mercadolivre_chat_messages(marketplace_integration_id, pack_id, seller_id, created_at);

CREATE TABLE IF NOT EXISTS public.mercadolivre_personalization_config (
    marketplace_integration_id integer PRIMARY KEY REFERENCES public.installed_integrations(id) ON DELETE CASCADE,
    enabled boolean NOT NULL DEFAULT false,
    capture_enabled boolean NOT NULL DEFAULT false,
    extraction_enabled boolean NOT NULL DEFAULT false,
    provider text NOT NULL DEFAULT 'gemini' CHECK (provider IN ('gemini','openrouter')),
    model_name text NOT NULL DEFAULT 'gemini-2.5-flash',
    fallback_provider text CHECK (fallback_provider IS NULL OR fallback_provider IN ('gemini','openrouter')),
    timeout_seconds integer NOT NULL DEFAULT 60 CHECK (timeout_seconds BETWEEN 1 AND 600),
    max_processing integer NOT NULL DEFAULT 50 CHECK (max_processing BETWEEN 1 AND 500),
    schedule_hour integer NOT NULL DEFAULT 9 CHECK (schedule_hour BETWEEN 0 AND 23),
    schedule_minute integer NOT NULL DEFAULT 0 CHECK (schedule_minute BETWEEN 0 AND 59),
    prompt_template text,
    last_scheduled_run_date date,
    updated_by bigint,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.mercadolivre_personalization_batches (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    marketplace_integration_id integer NOT NULL REFERENCES public.installed_integrations(id) ON DELETE CASCADE,
    pack_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
    total integer NOT NULL DEFAULT 0,
    processed integer NOT NULL DEFAULT 0,
    attempts integer NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'PENDING'
      CHECK (status IN ('PENDING','RUNNING','COMPLETED','FAILED')),
    force boolean NOT NULL DEFAULT false,
    error_message text,
    available_at timestamptz NOT NULL DEFAULT now(),
    lease_until timestamptz,
    created_by bigint,
    created_at timestamptz NOT NULL DEFAULT now(),
    started_at timestamptz,
    finished_at timestamptz
);
CREATE INDEX IF NOT EXISTS ix_ml_personalization_batches_account
  ON public.mercadolivre_personalization_batches(marketplace_integration_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ix_ml_personalization_batches_recovery
  ON public.mercadolivre_personalization_batches(marketplace_integration_id, status, available_at);

CREATE TABLE IF NOT EXISTS public.mercadolivre_personalization_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marketplace_integration_id integer NOT NULL REFERENCES public.installed_integrations(id) ON DELETE CASCADE,
    batch_id uuid REFERENCES public.mercadolivre_personalization_batches(id) ON DELETE SET NULL,
    pack_id text,
    pedido_id integer REFERENCES public.pedidos(id) ON DELETE SET NULL,
    executed_at timestamptz NOT NULL DEFAULT now(),
    status text NOT NULL,
    input_data text,
    model_result jsonb,
    error_message text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS ix_ml_personalization_logs_order
  ON public.mercadolivre_personalization_logs(marketplace_integration_id, pedido_id, executed_at DESC);

CREATE TABLE IF NOT EXISTS public.mercadolivre_personalizations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marketplace_integration_id integer NOT NULL REFERENCES public.installed_integrations(id) ON DELETE CASCADE,
    pedido_id integer NOT NULL REFERENCES public.pedidos(id) ON DELETE CASCADE,
    item_pedido_id integer NOT NULL REFERENCES public.itens_pedido(id) ON DELETE CASCADE,
    pack_id text NOT NULL,
    provider_order_id text NOT NULL,
    provider_item_id text,
    provider_message_id text,
    quantity_to_personalize integer NOT NULL DEFAULT 1 CHECK (quantity_to_personalize > 0),
    customization_name text,
    customization_initial text,
    status text NOT NULL CHECK (status IN ('SUCCESS','NEEDS_REVIEW','NO_PERSONALIZATION_FOUND')),
    reasoning text,
    context_hash text NOT NULL,
    source text NOT NULL DEFAULT 'ai' CHECK (source IN ('ai','manual')),
    confirmed boolean NOT NULL DEFAULT false,
    confirmed_by integer,
    confirmed_at timestamptz,
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (marketplace_integration_id, pedido_id, item_pedido_id, provider_item_id, context_hash)
);
CREATE INDEX IF NOT EXISTS ix_ml_personalizations_print
  ON public.mercadolivre_personalizations(pedido_id, item_pedido_id, confirmed, status);

ALTER TABLE public.mercadolivre_chat_inbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mercadolivre_chat_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mercadolivre_chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mercadolivre_personalization_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mercadolivre_personalization_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mercadolivre_personalization_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mercadolivre_personalizations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.mercadolivre_chat_inbox, public.mercadolivre_chat_conversations,
  public.mercadolivre_chat_messages, public.mercadolivre_personalization_config,
  public.mercadolivre_personalization_batches, public.mercadolivre_personalization_logs,
  public.mercadolivre_personalizations FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.mercadolivre_chat_inbox, public.mercadolivre_chat_conversations,
  public.mercadolivre_chat_messages, public.mercadolivre_personalization_config,
  public.mercadolivre_personalization_batches, public.mercadolivre_personalization_logs,
  public.mercadolivre_personalizations TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.mercadolivre_chat_inbox_id_seq,
  public.mercadolivre_personalization_logs_id_seq,
  public.mercadolivre_personalizations_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.persist_mercadolivre_personalization_results(
    p_integration_id integer,
    p_pack_id text,
    p_context_hash text,
    p_status text,
    p_needs_review boolean,
    p_records jsonb,
    p_log jsonb,
    p_batch_id uuid DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_record jsonb;
    v_pedido_id integer;
    v_item_id integer;
    v_rows integer := 0;
BEGIN
    IF p_status NOT IN ('SUCCESS', 'NEEDS_REVIEW', 'NO_PERSONALIZATION_FOUND') THEN
        RAISE EXCEPTION 'invalid Mercado Livre personalization status';
    END IF;
    IF jsonb_typeof(p_records) <> 'array' THEN
        RAISE EXCEPTION 'personalization records must be an array';
    END IF;
    DELETE FROM mercadolivre_personalizations
     WHERE marketplace_integration_id = p_integration_id
       AND pack_id = p_pack_id
       AND context_hash = p_context_hash
       AND source = 'ai'
       AND confirmed = FALSE;
    FOR v_record IN SELECT value FROM jsonb_array_elements(p_records) LOOP
        v_pedido_id := (v_record->>'pedido_id')::bigint;
        v_item_id := (v_record->>'item_pedido_id')::bigint;
        IF NOT EXISTS (
            SELECT 1 FROM pedidos p
            JOIN itens_pedido i ON i.id = v_item_id AND i.pedido_id = p.id
            WHERE p.id = v_pedido_id
              AND p.marketplace_integration_id = p_integration_id
              AND p.marketplace_module_id = (
                  SELECT lower(ii.module_id)
                    FROM installed_integrations ii
                   WHERE ii.id = p_integration_id
              )
        ) THEN
            RAISE EXCEPTION 'order/item does not belong to Mercado Livre integration %', p_integration_id;
        END IF;
        INSERT INTO mercadolivre_personalizations (
            marketplace_integration_id, pedido_id, item_pedido_id, pack_id,
            provider_order_id, provider_item_id, provider_message_id,
            quantity_to_personalize, customization_name, customization_initial,
            status, reasoning, context_hash, source, confirmed, details
        ) VALUES (
            p_integration_id, v_pedido_id, v_item_id, p_pack_id,
            v_record->>'provider_order_id', COALESCE(v_record->>'provider_item_id', 'local-item-' || v_item_id::text),
            v_record->>'provider_message_id', GREATEST(1, (v_record->>'quantity_to_personalize')::integer),
            NULLIF(v_record->>'customization_name', ''), NULLIF(v_record->>'customization_initial', ''),
            CASE WHEN p_needs_review THEN 'NEEDS_REVIEW' ELSE p_status END,
            v_record->>'reasoning', p_context_hash, COALESCE(v_record->>'source', 'ai'),
            FALSE, COALESCE(v_record->'details', '{}'::jsonb)
        ) ON CONFLICT (marketplace_integration_id, pedido_id, item_pedido_id, provider_item_id, context_hash)
        DO UPDATE SET provider_message_id = EXCLUDED.provider_message_id,
                      quantity_to_personalize = EXCLUDED.quantity_to_personalize,
                      customization_name = EXCLUDED.customization_name,
                      customization_initial = EXCLUDED.customization_initial,
                      status = EXCLUDED.status, reasoning = EXCLUDED.reasoning,
                      source = 'ai', confirmed = FALSE, confirmed_by = NULL,
                      confirmed_at = NULL, details = EXCLUDED.details,
                      updated_at = now();
        v_rows := v_rows + 1;
    END LOOP;
    UPDATE mercadolivre_chat_conversations
       SET context_hash = p_context_hash,
           ai_status = CASE WHEN p_needs_review THEN 'needs_review' ELSE lower(p_status) END,
           needs_review = p_needs_review OR p_status = 'NO_PERSONALIZATION_FOUND',
           last_ai_executed_at = now(), last_error = NULL, updated_at = now()
     WHERE marketplace_integration_id = p_integration_id AND pack_id = p_pack_id;
    INSERT INTO mercadolivre_personalization_logs (
        marketplace_integration_id, batch_id, pack_id, status,
        input_data, model_result, metadata
    ) VALUES (
        p_integration_id, p_batch_id, p_pack_id, lower(p_status),
        p_log->>'input_data', p_log->'model_result', COALESCE(p_log->'metadata', '{}'::jsonb)
    );
    RETURN jsonb_build_object('saved', v_rows, 'status', p_status, 'context_hash', p_context_hash);
END;
$$;
REVOKE ALL ON FUNCTION public.persist_mercadolivre_personalization_results(integer,text,text,text,boolean,jsonb,jsonb,uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.persist_mercadolivre_personalization_results(integer,text,text,text,boolean,jsonb,jsonb,uuid)
  TO service_role;
