-- Durable per-pack progress and serialized batch execution per Mercado Livre account.
ALTER TABLE public.mercadolivre_chat_conversations
  ADD COLUMN IF NOT EXISTS current_context_hash text;

ALTER TABLE public.mercadolivre_personalization_batches
  ADD COLUMN IF NOT EXISTS run_token uuid;

ALTER TABLE public.mercadolivre_personalization_batches
  ADD COLUMN IF NOT EXISTS created_by bigint;

CREATE TABLE IF NOT EXISTS public.mercadolivre_personalization_batch_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id uuid NOT NULL REFERENCES public.mercadolivre_personalization_batches(id) ON DELETE CASCADE,
  marketplace_integration_id integer NOT NULL REFERENCES public.installed_integrations(id) ON DELETE CASCADE,
  pack_id text NOT NULL,
  status text NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED')),
  attempts integer NOT NULL DEFAULT 0,
  error_message text,
  started_at timestamptz,
  finished_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (batch_id, pack_id)
);

CREATE INDEX IF NOT EXISTS ix_ml_personalization_batch_items_recovery
  ON public.mercadolivre_personalization_batch_items(batch_id, status, pack_id);
CREATE INDEX IF NOT EXISTS ix_ml_personalizations_order_context
  ON public.mercadolivre_personalizations(marketplace_integration_id, pedido_id, context_hash);
CREATE INDEX IF NOT EXISTS ix_ml_orders_account_status_date
  ON public.pedidos(marketplace_integration_id, situacao_pedido_id, data_venda DESC, id DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_ml_personalization_one_running_batch_per_account
  ON public.mercadolivre_personalization_batches(marketplace_integration_id)
  WHERE status = 'RUNNING';

CREATE OR REPLACE VIEW public.view_mercadolivre_personalization_order_summary
WITH (security_invoker = true) AS
WITH eligible_items AS (
  SELECT i.id AS item_pedido_id, i.pedido_id, GREATEST(1, COALESCE(i.quantidade, 1)) AS quantity
    FROM public.itens_pedido i
   WHERE i.personalizado IS TRUE
      OR lower(COALESCE(i.titulo_anuncio, '') || ' ' || COALESCE(i.descricao, '')) LIKE '%personaliz%'
),
current_results AS (
  SELECT p.marketplace_integration_id, p.pedido_id, p.item_pedido_id, p.context_hash,
         sum(p.quantity_to_personalize) AS quantity,
         bool_or(COALESCE(NULLIF(trim(p.customization_name), ''),
                          NULLIF(trim(p.customization_initial), '')) IS NOT NULL) AS has_name,
         bool_or(p.status = 'NO_PERSONALIZATION_FOUND'
                 OR (p.status = 'SUCCESS' AND p.customization_name IS NULL
                     AND p.customization_initial IS NULL)) AS has_no_name
    FROM public.mercadolivre_personalizations p
   WHERE p.confirmed IS TRUE OR p.status IN ('SUCCESS', 'NEEDS_REVIEW', 'NO_PERSONALIZATION_FOUND')
   GROUP BY p.marketplace_integration_id, p.pedido_id, p.item_pedido_id, p.context_hash
),
order_summary AS (
  SELECT p.id, p.marketplace_integration_id, p.numero_pedido, p.codigo_pedido_externo,
         p.marketplace_order_id, p.data_venda, p.situacao_pedido_id, p.cliente_nome,
         p.buyer_username, p.informacoes_cliente, p.message_to_seller,
         c.pack_id, c.last_message_at, c.last_ai_executed_at, c.ai_status,
         c.needs_review, c.last_error, c.current_context_hash,
         EXISTS (SELECT 1 FROM public.mercadolivre_chat_messages m
                  WHERE m.marketplace_integration_id = p.marketplace_integration_id
                    AND m.pack_id = c.pack_id) AS has_chat_messages,
         EXISTS (SELECT 1 FROM public.mercadolivre_chat_messages m
                  WHERE m.marketplace_integration_id = p.marketplace_integration_id
                    AND m.pack_id = c.pack_id AND m.sender_role = 'buyer') AS has_buyer_chat,
         EXISTS (SELECT 1 FROM public.mercadolivre_chat_messages m
                  WHERE m.marketplace_integration_id = p.marketplace_integration_id
                    AND m.pack_id = c.pack_id AND m.sender_role = 'unknown') AS chat_context_ambiguous,
         (SELECT max(m.created_at) FROM public.mercadolivre_chat_messages m
           WHERE m.marketplace_integration_id = p.marketplace_integration_id
             AND m.pack_id = c.pack_id AND m.sender_role = 'buyer') AS last_buyer_message_at,
         EXISTS (SELECT 1 FROM eligible_items i WHERE i.pedido_id = p.id) AS has_personalized_item,
         (c.current_context_hash IS NOT NULL AND EXISTS (SELECT 1 FROM eligible_items i
                  LEFT JOIN current_results r ON r.marketplace_integration_id = p.marketplace_integration_id
                    AND r.pedido_id = p.id AND r.item_pedido_id = i.item_pedido_id
                    AND r.context_hash = c.current_context_hash
                 WHERE i.pedido_id = p.id
                   AND COALESCE(r.quantity, 0) <> i.quantity)) AS extraction_missing,
         EXISTS (SELECT 1 FROM current_results r
                  WHERE r.marketplace_integration_id = p.marketplace_integration_id
                    AND r.pedido_id = p.id AND r.context_hash = c.current_context_hash
                    AND r.has_name) AS has_identified_name,
         EXISTS (SELECT 1 FROM current_results r
                  WHERE r.marketplace_integration_id = p.marketplace_integration_id
                    AND r.pedido_id = p.id AND r.context_hash = c.current_context_hash
                    AND r.has_no_name) AS has_no_name
    FROM public.pedidos p
    LEFT JOIN LATERAL (
      SELECT candidate.*
        FROM public.mercadolivre_chat_conversations candidate
       WHERE candidate.marketplace_integration_id = p.marketplace_integration_id
         AND (candidate.order_ids @> jsonb_build_array(COALESCE(p.marketplace_order_id, p.codigo_pedido_externo))
              OR candidate.pack_id = COALESCE(p.marketplace_order_id, p.codigo_pedido_externo))
       ORDER BY candidate.last_message_at DESC NULLS LAST
       LIMIT 1
    ) c ON true
   WHERE p.marketplace_integration_id IS NOT NULL
     AND p.situacao_pedido_id IN (2, 4)
)
SELECT *,
       (has_buyer_chat OR NULLIF(trim(COALESCE(message_to_seller, '')), '') IS NOT NULL) AS has_buyer_message,
       (COALESCE(last_error, '') <> '' OR extraction_missing OR
        (last_ai_executed_at IS NULL AND
          (has_chat_messages OR NULLIF(trim(COALESCE(message_to_seller, '')), '') IS NOT NULL)) OR
        (last_buyer_message_at IS NOT NULL AND last_ai_executed_at IS NOT NULL
          AND last_buyer_message_at > last_ai_executed_at)) AS needs_ai_processing
  FROM order_summary
 WHERE has_personalized_item;

REVOKE ALL ON public.view_mercadolivre_personalization_order_summary FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.view_mercadolivre_personalization_order_summary TO service_role;

CREATE OR REPLACE VIEW public.view_shopee_personalization_order_summary
WITH (security_invoker = true) AS
SELECT v.id, p.marketplace_integration_id, v.numero_pedido, v.numero_loja,
       v.nome_cliente, v.buyer_username, v.data_pedido, v.has_chat_messages,
       v.needs_ai_processing, v.ai_status,
       EXISTS (
         SELECT 1 FROM jsonb_array_elements(COALESCE(v.itens, '[]'::jsonb)) AS item(value)
         CROSS JOIN LATERAL jsonb_array_elements(COALESCE(item.value->'personalizations', '[]'::jsonb)) AS personalization(value)
         WHERE NULLIF(trim(COALESCE(personalization.value->>'customization_name',
                                    personalization.value->>'customization_initial', '')), '') IS NOT NULL
       ) AS has_identified_name,
       (upper(COALESCE(v.ai_status, '')) = 'NO_PERSONALIZATION_FOUND' OR EXISTS (
         SELECT 1 FROM jsonb_array_elements(COALESCE(v.itens, '[]'::jsonb)) AS item(value)
         CROSS JOIN LATERAL jsonb_array_elements(COALESCE(item.value->'personalizations', '[]'::jsonb)) AS personalization(value)
         WHERE upper(COALESCE(personalization.value->>'status', '')) = 'NO_PERSONALIZATION_FOUND'
            OR (upper(COALESCE(personalization.value->>'status', '')) = 'SUCCESS'
                AND NULLIF(trim(COALESCE(personalization.value->>'customization_name',
                                         personalization.value->>'customization_initial', '')), '') IS NULL)
       )) AS has_no_name
  FROM public.view_vendas_personalizadas_v3 v
  JOIN public.pedidos p ON p.id = v.id;

REVOKE ALL ON public.view_shopee_personalization_order_summary FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.view_shopee_personalization_order_summary TO service_role;

ALTER TABLE public.mercadolivre_personalization_batch_items ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.mercadolivre_personalization_batch_items FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.mercadolivre_personalization_batch_items TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.mercadolivre_personalization_batch_items_id_seq TO service_role;

-- Existing hashes point at the last completed extraction. The last-buyer-message
-- timestamp remains the signal that a newer context must be processed.
UPDATE public.mercadolivre_chat_conversations
   SET current_context_hash = context_hash
 WHERE current_context_hash IS NULL AND context_hash IS NOT NULL;

INSERT INTO public.mercadolivre_personalization_batch_items
  (batch_id, marketplace_integration_id, pack_id)
SELECT b.id, b.marketplace_integration_id, item.pack_id
  FROM public.mercadolivre_personalization_batches AS b
 CROSS JOIN LATERAL jsonb_array_elements_text(COALESCE(b.pack_ids, '[]'::jsonb)) AS item(pack_id)
 WHERE b.status NOT IN ('COMPLETED', 'FAILED')
ON CONFLICT (batch_id, pack_id) DO NOTHING;
