-- Atomic marketplace lifecycle projection and audit trail.

ALTER TABLE public.pedidos
  ADD COLUMN IF NOT EXISTS marketplace_order_status TEXT,
  ADD COLUMN IF NOT EXISTS marketplace_payment_status TEXT,
  ADD COLUMN IF NOT EXISTS marketplace_shipping_status TEXT,
  ADD COLUMN IF NOT EXISTS marketplace_shipping_substatus TEXT,
  ADD COLUMN IF NOT EXISTS marketplace_lifecycle_stage TEXT,
  ADD COLUMN IF NOT EXISTS marketplace_status_updated_at TIMESTAMPTZ;

ALTER TABLE public.webhook_events
  ADD COLUMN IF NOT EXISTS provider_topic TEXT,
  ADD COLUMN IF NOT EXISTS provider_resource TEXT,
  ADD COLUMN IF NOT EXISTS resolved_order_id TEXT,
  ADD COLUMN IF NOT EXISTS provider_updated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS lifecycle_stage TEXT;

INSERT INTO public.situacoes_pedido (
  id, nome, descricao, flag_reserva_estoque, flag_fatura, flag_cancelado,
  cor_status, created_at, updated_at
) VALUES (
  8, 'Devolvido', 'Pedido devolvido ou reembolsado apos expedicao',
  false, false, true, '#8b5cf6', now(), now()
)
ON CONFLICT (id) DO UPDATE SET
  nome = EXCLUDED.nome, descricao = EXCLUDED.descricao,
  flag_cancelado = EXCLUDED.flag_cancelado, cor_status = EXCLUDED.cor_status,
  updated_at = now();

SELECT setval(
  pg_get_serial_sequence('public.situacoes_pedido', 'id'),
  GREATEST(
    (SELECT max(id) FROM public.situacoes_pedido),
    (SELECT last_value FROM public.situacoes_pedido_id_seq),
    8
  ),
  true
);

UPDATE public.integration_status_mappings
SET internal_situacao_pedido_id = 4,
    triggers_demand_consolidation = true,
    config = '{"action":"sync_and_consolidate"}'::jsonb,
    updated_at = now()
WHERE module_id = 'mercadolivre' AND integration_id IS NULL
  AND status_domain = 'shipping' AND external_status_id = 'ready_to_ship';

INSERT INTO public.integration_status_mappings (
  module_id, integration_id, status_domain, external_status_id,
  external_status_name, internal_situacao_pedido_id,
  triggers_demand_consolidation, config
)
SELECT 'mercadolivre', NULL, 'shipping', 'ready_to_ship',
       'ready_to_ship', 4, true, '{"action":"sync_and_consolidate"}'::jsonb
WHERE NOT EXISTS (
  SELECT 1 FROM public.integration_status_mappings
  WHERE module_id = 'mercadolivre' AND integration_id IS NULL
    AND status_domain = 'shipping' AND external_status_id = 'ready_to_ship'
);

CREATE TABLE IF NOT EXISTS public.marketplace_order_transitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL REFERENCES public.pedidos(id) ON DELETE CASCADE,
  webhook_event_id BIGINT REFERENCES public.webhook_events(id) ON DELETE SET NULL,
  provider_event_id TEXT,
  module_id TEXT NOT NULL,
  external_order_id TEXT NOT NULL,
  lifecycle_stage TEXT NOT NULL,
  previous_situacao_pedido_id INTEGER,
  requested_situacao_pedido_id INTEGER,
  applied_situacao_pedido_id INTEGER,
  decision TEXT NOT NULL,
  reason TEXT,
  provider_updated_at TIMESTAMPTZ,
  provider_state JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_marketplace_order_transition_provider_event
  ON public.marketplace_order_transitions(module_id, provider_event_id)
  WHERE provider_event_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_marketplace_order_transitions_pedido_created
  ON public.marketplace_order_transitions(pedido_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.marketplace_order_effects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL REFERENCES public.pedidos(id) ON DELETE CASCADE,
  transition_id BIGINT NOT NULL REFERENCES public.marketplace_order_transitions(id) ON DELETE CASCADE,
  effect_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  processed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (transition_id, effect_type)
);

ALTER TABLE public.marketplace_order_transitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketplace_order_effects ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.marketplace_order_transitions FROM anon, authenticated;
REVOKE ALL ON public.marketplace_order_effects FROM anon, authenticated;
GRANT ALL ON public.marketplace_order_transitions TO service_role;
GRANT ALL ON public.marketplace_order_effects TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.marketplace_order_transitions_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.marketplace_order_effects_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.apply_marketplace_order_event(
  p_order JSONB,
  p_snapshot JSONB DEFAULT NULL,
  p_refs JSONB DEFAULT '[]'::jsonb,
  p_event JSONB DEFAULT '{}'::jsonb,
  p_projection_enabled BOOLEAN DEFAULT false
)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  v_module_id TEXT := lower(NULLIF(p_order->>'marketplace_module_id', ''));
  v_external_order_id TEXT := NULLIF(p_order->>'marketplace_order_id', '');
  v_existing_id BIGINT;
  v_pedido_id BIGINT;
  v_previous_status INTEGER;
  v_target_status INTEGER := NULLIF(p_event->>'target_situacao_pedido_id', '')::INTEGER;
  v_applied_status INTEGER;
  v_stage TEXT := COALESCE(NULLIF(p_event->>'lifecycle_stage', ''), 'unknown');
  v_provider_updated_at TIMESTAMPTZ := NULLIF(p_event->>'observed_at', '')::TIMESTAMPTZ;
  v_current_provider_updated_at TIMESTAMPTZ;
  v_decision TEXT := 'external_state_only';
  v_transition_id BIGINT;
BEGIN
  IF v_module_id IS NULL OR v_external_order_id IS NULL THEN
    RAISE EXCEPTION 'marketplace_module_id and marketplace_order_id are required';
  END IF;

  SELECT id, situacao_pedido_id INTO v_existing_id, v_previous_status
  FROM public.pedidos
  WHERE marketplace_module_id = v_module_id
    AND marketplace_order_id = v_external_order_id
  FOR UPDATE;

  v_pedido_id := public.upsert_canonical_order(
    p_order - 'situacao_pedido_id',
    p_snapshot,
    p_refs
  );

  SELECT situacao_pedido_id, marketplace_status_updated_at
  INTO v_previous_status, v_current_provider_updated_at
  FROM public.pedidos WHERE id = v_pedido_id FOR UPDATE;

  IF v_provider_updated_at IS NOT NULL
     AND v_current_provider_updated_at IS NOT NULL
     AND v_provider_updated_at < v_current_provider_updated_at THEN
    v_decision := 'ignored_stale';
  ELSE
    UPDATE public.pedidos SET
      marketplace_order_status = COALESCE(NULLIF(p_event->>'order_status', ''), marketplace_order_status),
      marketplace_payment_status = COALESCE(NULLIF(p_event->>'payment_status', ''), marketplace_payment_status),
      marketplace_shipping_status = COALESCE(NULLIF(p_event->>'shipping_status', ''), marketplace_shipping_status),
      marketplace_shipping_substatus = COALESCE(NULLIF(p_event->>'shipping_substatus', ''), marketplace_shipping_substatus),
      marketplace_lifecycle_stage = v_stage,
      marketplace_status_updated_at = COALESCE(v_provider_updated_at, marketplace_status_updated_at, now()),
      informacoes_cliente = CASE
        WHEN COALESCE(p_order->'informacoes_cliente', p_order->'customer', '{}'::jsonb) = '{}'::jsonb
          THEN informacoes_cliente
        ELSE COALESCE(p_order->'informacoes_cliente', p_order->'customer')
      END,
      updated_at = now()
    WHERE id = v_pedido_id;

    IF (v_existing_id IS NULL OR p_projection_enabled) AND v_target_status IS NOT NULL THEN
      v_applied_status := CASE
        WHEN v_target_status = 8 THEN 8
        WHEN v_previous_status = 8 THEN 8
        WHEN v_target_status = 7 AND v_previous_status IN (5, 6) THEN 8
        WHEN v_target_status = 7 THEN 7
        WHEN v_previous_status IN (6, 7) THEN v_previous_status
        WHEN v_target_status = 6 THEN 6
        WHEN v_target_status = 5 THEN 5
        WHEN v_target_status = 4 AND v_previous_status = 3 THEN 3
        WHEN v_target_status = 4 AND COALESCE(v_previous_status, 1) IN (1, 2, 4) THEN 4
        WHEN v_target_status = 2 AND COALESCE(v_previous_status, 1) IN (1, 2) THEN 2
        WHEN v_target_status = 1 AND COALESCE(v_previous_status, 1) = 1 THEN 1
        ELSE v_previous_status
      END;
      IF v_applied_status IS DISTINCT FROM v_previous_status THEN
        UPDATE public.pedidos SET situacao_pedido_id = v_applied_status, updated_at = now()
        WHERE id = v_pedido_id;
        v_decision := 'applied';
      ELSE
        v_decision := 'ignored_regression';
      END IF;
    ELSIF v_target_status IS NULL THEN
      v_decision := 'unmapped';
    END IF;
  END IF;

  SELECT situacao_pedido_id INTO v_applied_status FROM public.pedidos WHERE id = v_pedido_id;

  INSERT INTO public.marketplace_order_transitions (
    pedido_id, webhook_event_id, provider_event_id, module_id,
    external_order_id, lifecycle_stage, previous_situacao_pedido_id,
    requested_situacao_pedido_id, applied_situacao_pedido_id, decision,
    reason, provider_updated_at, provider_state
  ) VALUES (
    v_pedido_id, NULLIF(p_event->>'webhook_event_id', '')::BIGINT,
    NULLIF(p_event->>'provider_event_id', ''), v_module_id,
    v_external_order_id, v_stage, v_previous_status, v_target_status,
    v_applied_status, v_decision, p_event->>'reason',
    v_provider_updated_at, p_event
  )
  ON CONFLICT (module_id, provider_event_id)
    WHERE provider_event_id IS NOT NULL
  DO UPDATE SET webhook_event_id = COALESCE(
    EXCLUDED.webhook_event_id,
    public.marketplace_order_transitions.webhook_event_id
  )
  RETURNING id INTO v_transition_id;

  IF v_decision = 'applied' AND v_applied_status IN (7, 8) THEN
    INSERT INTO public.marketplace_order_effects (
      pedido_id, transition_id, effect_type, payload
    ) VALUES (
      v_pedido_id, v_transition_id, 'alert_active_demands',
      jsonb_build_object(
        'situacao_pedido_id', v_applied_status,
        'lifecycle_stage', v_stage,
        'external_order_id', v_external_order_id
      )
    )
    ON CONFLICT (transition_id, effect_type) DO NOTHING;
  END IF;

  RETURN jsonb_build_object(
    'pedido_id', v_pedido_id, 'transition_id', v_transition_id,
    'decision', v_decision,
    'previous_situacao_pedido_id', v_previous_status,
    'situacao_pedido_id', v_applied_status,
    'lifecycle_stage', v_stage
  );
END;
$$;

REVOKE ALL ON FUNCTION public.apply_marketplace_order_event(JSONB, JSONB, JSONB, JSONB, BOOLEAN) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.apply_marketplace_order_event(JSONB, JSONB, JSONB, JSONB, BOOLEAN) TO service_role;

CREATE OR REPLACE FUNCTION public.process_marketplace_order_effect(p_effect_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  v_effect public.marketplace_order_effects%ROWTYPE;
  v_link RECORD;
  v_alert_count INTEGER := 0;
  v_is_returned BOOLEAN;
BEGIN
  SELECT * INTO v_effect
  FROM public.marketplace_order_effects
  WHERE id = p_effect_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'marketplace_order_effect % not found', p_effect_id;
  END IF;
  IF v_effect.status = 'processed' THEN
    RETURN jsonb_build_object('effect_id', p_effect_id, 'status', 'processed', 'alerts', 0);
  END IF;

  v_is_returned := COALESCE(v_effect.payload->>'lifecycle_stage', '') = 'returned';
  FOR v_link IN
    SELECT dp.demanda_id
    FROM public.demandas_pedidos dp
    JOIN public.demandas_producao d ON d.id = dp.demanda_id
    WHERE dp.pedido_id = v_effect.pedido_id
      AND d.status IN ('AGUARDANDO', 'EM_PRODUCAO', 'COLETA_PARCIAL', 'COLETADO')
  LOOP
    INSERT INTO public.alertas_demanda (
      demanda_id, tipo_alerta, severidade, titulo, mensagem,
      dados_impacto, requer_acao, created_at
    ) VALUES (
      v_link.demanda_id,
      CASE WHEN v_is_returned THEN 'PEDIDO_DEVOLVIDO' ELSE 'PEDIDO_CANCELADO' END,
      'media',
      CASE WHEN v_is_returned THEN 'Pedido devolvido na demanda' ELSE 'Pedido cancelado na demanda' END,
      format(
        'Pedido %s foi %s pelo marketplace; revise a demanda.',
        COALESCE(v_effect.payload->>'external_order_id', v_effect.pedido_id::text),
        CASE WHEN v_is_returned THEN 'devolvido' ELSE 'cancelado' END
      ),
      jsonb_build_object(
        'pedido_id', v_effect.pedido_id,
        'transition_id', v_effect.transition_id,
        'effect_id', v_effect.id,
        'lifecycle_stage', v_effect.payload->>'lifecycle_stage'
      ),
      true,
      now()
    );
    UPDATE public.demandas_producao
       SET requer_revisao = true, updated_at = now()
     WHERE id = v_link.demanda_id;
    v_alert_count := v_alert_count + 1;
  END LOOP;

  INSERT INTO public.eventos_pedido (
    pedido_id, tipo_evento, descricao, status_para, metadata, created_at
  ) VALUES (
    v_effect.pedido_id,
    CASE WHEN v_is_returned THEN 'ORDER_RETURNED_MARKETPLACE' ELSE 'ORDER_CANCELLED_MARKETPLACE' END,
    CASE WHEN v_is_returned THEN 'Pedido devolvido pelo marketplace' ELSE 'Pedido cancelado pelo marketplace' END,
    CASE WHEN v_is_returned THEN '8' ELSE '7' END,
    jsonb_build_object('transition_id', v_effect.transition_id, 'effect_id', v_effect.id),
    now()
  );

  UPDATE public.marketplace_order_effects
     SET status = 'processed', processed_at = now(), updated_at = now(),
         attempt_count = attempt_count + 1, last_error = NULL
   WHERE id = p_effect_id;

  RETURN jsonb_build_object(
    'effect_id', p_effect_id, 'status', 'processed', 'alerts', v_alert_count
  );
END;
$$;

REVOKE ALL ON FUNCTION public.process_marketplace_order_effect(BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.process_marketplace_order_effect(BIGINT) TO service_role;

UPDATE public.configuracoes_aplicacao
SET valor = jsonb_set(
  jsonb_set(
    CASE WHEN jsonb_typeof(valor) = 'string' THEN (valor #>> '{}')::jsonb ELSE valor END,
    '{task_schedules,process-marketplace-lifecycle-effects}',
    '{"enabled":true,"schedule_seconds":30,"description":"Entrega alertas idempotentes de cancelamento e devolucao","task_name":"nistiprint_shared.services.marketplace_lifecycle_tasks.process_pending_effects"}'::jsonb,
    true
  ),
  '{task_schedules,reconcile-marketplace-lifecycle}',
  '{"enabled":false,"schedule_seconds":300,"description":"Backfill marketplace em modo comparacao","task_name":"nistiprint_shared.services.marketplace_lifecycle_tasks.reconcile_marketplace_lifecycle","kwargs":{"dry_run":true,"days":60,"limit":100,"offset":0}}'::jsonb,
  true
)
WHERE nome = 'celery_task_schedules';
