[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx/error.log
stdout_logfile=/var/log/nginx/access.log
priority=1
user=root

[program:gunicorn]
command=python -m gunicorn --bind 127.0.0.1:5000 --workers 1 --threads 4 --timeout 0 wsgi:app
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/gunicorn/error.log
stdout_logfile=/var/log/gunicorn/access.log
priority=2
user=root
environment=FLASK_ENV="production",PORT="5000"
